# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5bafa71218afd91fed98d272b880c797baaa2cdf53e77743b48a94ddc5938408d4b4fd4f3dd6a338738a13f413537d227b5bb33a95bbc548080f0bdf2ba40d7

test:
  secret_key_base: a7c9c5a391d301399108c51a127a5eff5cb4133126ccc1ea082a547791fdd8f8a7d57f8421b8ecfaa0a17f3bc1ba50e51eef1a78fc763a82467e5567e74af76e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
